version: "3.9"

# won't add fan/humidifier controls to docker-compose-wsl since, well, not a pi
services:
  web:
    build:
      context: .
      network: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECRET_KEY=django-insecure-=j2$$0qjfv%!43rml&l7k2luuy5n-7+%@h1w20z#c2y)5z4e7^9"
  asgi:
    build:
      context: .
      network: .
    command: mqttasgi -H mqtt -p 1883 config.asgi:application
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web
      - mosquitto
    environment:
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECRET_KEY=django-insecure-=j2$$0qjfv%!43rml&l7k2luuy5n-7+%@h1w20z#c2y)5z4e7^9"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
  celery:
    build:
      context: .
      network: host
    command: celery --app config worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=django-insecure-=j2$$0qjfv%!43rml&l7k2luuy5n-7+%@h1w20z#c2y)5z4e7^9
      - DJANGO_ALLOWED_HOSTS=* #localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
  celery-beat:
    build:
      context: .
      network: host
    command: celery -A config beat -l info
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=django-insecure-=j2$$0qjfv%!43rml&l7k2luuy5n-7+%@h1w20z#c2y)5z4e7^9
      - DJANGO_ALLOWED_HOSTS=* #localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  redis:
    image: redis:6-alpine
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  # TODO: need to get the and topics from environment/config
  # use a .env file
  fan-control:
    build:
      context: ./fan-control/
      network: host
    devices:
      - /dev/mem:/dev/mem
      - /dev/gpiomem:/dev/gpiomem
    command: python3 fan-control.py --host mqtt --gpio 12 16 --topics "tent1/fan1/test" "tent1/fan2/test"
    depends_on:
      - mosquitto
      - web
  humidifier-control:
    build:
      context: ./humidifier-control/
      network: host
    devices:
      - /dev/mem:/dev/mem
      - /dev/gpiomem:/dev/gpiomem
    command: python3 humidifier-control.py --host mqtt --pin 5 --topic "tent1/humidifier/test"
    depends_on:
      - mosquitto
      - web
  grafana:
    image: grafana/grafana
    ports: 
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  postgres_data:
  grafana_data:
