version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECRET_KEY=django-insecure-=j2$$0qjfv%!43rml&l7k2luuy5n-7+%@h1w20z#c2y)5z4e7^9"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
#  mosquitto:
#    image: eclipse-mosquitto
#    # network_mode: host
#    ports:
#      - 21883:1883
#    volumes:
#      - ./mosquitto/conf:/mosquitto/conf
#      - ./mosquitto/data:/mosquitto/data
#      - ./mosquitto/log:/mosquitto/log
volumes:
  postgres_data:

    # for now we'll stick to using test.mosquitto.org
    # should figure this out
    # using docker inspect homegrowing_mosquitto_1 to get ip address
    # that gave 172.20.0.2 which led to connect refused
    # might be able to use "homegrowing_mosquitto_1" or name field instead of ip --this is correct
    # stackoverflow window open which might help & might want to change mosquitto port mappings
