# Pull base image
FROM python:3.10.5-bullseye AS base

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install dependencies
COPY ./requirements-min.txt .
RUN pip install -r requirements-min.txt

# Copy project
COPY . .
