# Generated by Django 4.0.5 on 2022-06-21 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.sensorhost')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.sensormetric')),
            ],
        ),
    ]
