# Generated by Django 4.0.5 on 2022-07-02 21:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('min_humidity', models.FloatField()),
                ('max_humidity', models.FloatField()),
                ('min_temperature', models.FloatField()),
                ('max_temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.sensorhost')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.sensormetric')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('growth_stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.growthstage')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
