# Generated by Django 4.0.5 on 2022-07-03 00:25

from django.db import migrations


def populate_growth_stages(apps, schema_editor):
    model = apps.get_model("monitoring", "GrowthStage")
    model.objects.create(
        name="Seedling",
        min_humidity=65,
        max_humidity=70,
        min_temperature=20,
        max_temperature=25,
    )
    model.objects.create(
        name="Vegetating1",
        min_humidity=61,
        max_humidity=65,
        min_temperature=22,
        max_temperature=28,
    )
    model.objects.create(
        name="Vegetating2",
        min_humidity=58,
        max_humidity=62,
        min_temperature=22,
        max_temperature=28,
    )
    model.objects.create(
        name="Flowering1",
        min_humidity=48,
        max_humidity=52,
        min_temperature=20,
        max_temperature=26,
    )
    model.objects.create(
        name="Flowering2",
        min_humidity=28,
        max_humidity=32,
        min_temperature=18,
        max_temperature=23,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [migrations.RunPython(populate_growth_stages)]
