# Generated by Django 4.0.5 on 2022-06-29 18:55

from django.db import migrations


def populate_growth_stages(apps, schema_editor):
    GrowthStage = apps.get_model("monitoring", "GrowthStage")
    GrowthStage.objects.create(
        name="Seedling",
        min_humidity=65,
        max_humidity=70,
        min_temperature=20,
        max_temperature=25,
    )
    GrowthStage.objects.create(
        name="Vegetating1",
        min_humidity=61,
        max_humidity=66,
        min_temperature=22,
        max_temperature=28,
    )
    GrowthStage.objects.create(
        name="Vegetating2",
        min_humidity=58,
        max_humidity=62,
        min_temperature=22,
        max_temperature=28,
    )
    GrowthStage.objects.create(
        name="Flowering1",
        min_humidity=48,
        max_humidity=52,
        min_temperature=20,
        max_temperature=26,
    )
    GrowthStage.objects.create(
        name="Flowering2",
        min_humidity=30,
        max_humidity=35,
        min_temperature=20,
        max_temperature=23,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_growthstage_alter_sensordata_created_at_and_more"),
    ]

    operations = [migrations.RunPython(populate_growth_stages)]
