# Generated by Django 4.1.5 on 2023-01-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
