# Generated by Django 4.1.5 on 2023-01-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
