# Generated by Django 4.1.5 on 2023-01-31 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_device_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthstage',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthstage',
            name='light_hours',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MaxValueValidator(24)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='growthstage',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
