# Generated by Django 4.1.6 on 2023-02-08 15:43

from django.db import migrations

sql = """CREATE VIEW monitoring_sensordata_view AS 
select d.id AS data_id,
h.host, m.metric, d.data, d.created_at
from ((monitoring_sensordata d
join monitoring_sensorhost h on ((d.host_id = h.id)))
join monitoring_sensormetric m on ((d.metric_id = m.id)));"""
rev_sql = "DROP VIEW monitoring_sensordata_view;"


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0007_growthstage_end_time_growthstage_light_hours_and_more"),
    ]

    operations = [migrations.RunSQL(sql=sql, reverse_sql=rev_sql)]
