# Generated by Django 4.1.6 on 2023-02-08 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_create_sensor_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDataView',
            fields=[
                ('data_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=255)),
                ('data', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monitoring_sensordata_view',
                'managed': False,
            },
        ),
    ]
