# Generated by Django 4.1.6 on 2023-02-08 18:57

from django.db import migrations

def populate_initial_crontabs(apps, schema_editor):
    model = apps.get_model('django_celery_beat', 'CrontabSchedule')

    model.objects.get_or_create(minute="*/1", timezone="US/Eastern")
    model.objects.get_or_create(minute="*/5", timezone="US/Eastern")
    model.objects.get_or_create(minute="*/15", timezone="US/Eastern")


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_sensordataview'),
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
    ]

    operations = [migrations.RunPython(populate_initial_crontabs)
    ]
