# Generated by Django 4.1.6 on 2023-02-08 19:54
import json

from django.db import migrations


def populate_basic_periodic_tasks(apps, schema_editor):
    crontab = apps.get_model("django_celery_beat", "CrontabSchedule")
    task = apps.get_model("django_celery_beat", "PeriodicTask")
    every_minute = crontab.objects.get(minute="*/1")
    task.objects.get_or_create(
        crontab=every_minute,
        name="humidity_rolling_avg",
        task="monitoring.tasks.climate_monitoring",
        args=json.dumps(["humidity"]),
    )
    task.objects.get_or_create(
        crontab=every_minute,
        name="temperature_rolling_avg",
        task="monitoring.tasks.climate_monitoring",
        args=json.dumps(["temperature"]),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0010_load_initial_crontabs"),
        ("django_celery_beat", "0016_alter_crontabschedule_timezone"),
    ]

    operations = [migrations.RunPython(populate_basic_periodic_tasks)]
