# Generated by Django 4.1.6 on 2023-02-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_load_initial_crontabs'),
    ]

    operations = [
    ]
